import Link from "next/link";
import { getSql, type StoredRecord } from "@/lib/db";
import VerifyClient from "./VerifyClient";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;
export const fetchCache = "force-no-store";

export const metadata = {
  title: "Verify — Cognitive Integrity Lab",
};

export default async function VerifyPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  let record: StoredRecord | null = null;
  try {
    const sql = getSql();
    const rows = (await sql`
      SELECT id, receipt_canonical, signature
      FROM compositions
      WHERE id = ${id}
      LIMIT 1
    `) as unknown as StoredRecord[];
    if (rows.length > 0) record = rows[0];
  } catch (err) {
    console.error("Verify lookup failed:", err);
  }

  if (!record) {
    return (
      <main style={pageStyle}>
        <div style={notFoundBadgeStyle}>Receipt not found</div>
        <p style={mutedStyle}>
          This verification link points to a receipt that does not exist on
          this site. The link may be malformed, mistyped, or generated by a
          different issuer.
        </p>
        <p style={mutedStyle}>
          <Link href="/about" style={{ color: "#6b6b6b", textDecoration: "underline" }}>
            About this site
          </Link>
        </p>
      </main>
    );
  }

  return (
    <VerifyClient
      receiptCanonical={record.receipt_canonical}
      signature={record.signature}
    />
  );
}

const pageStyle: React.CSSProperties = {
  maxWidth: 720,
  margin: "0 auto",
  padding: "3rem 1.5rem",
  display: "flex",
  flexDirection: "column",
  gap: "1.5rem",
};

const mutedStyle: React.CSSProperties = {
  margin: 0,
  color: "#6b6b6b",
  fontSize: "0.9rem",
};

const notFoundBadgeStyle: React.CSSProperties = {
  alignSelf: "flex-start",
  padding: "0.5rem 0.9rem",
  fontSize: "0.95rem",
  fontWeight: 600,
  color: "#7a1a1a",
  background: "#fdecec",
  border: "1px solid #f5c4c4",
  borderRadius: 6,
};
